Repository PetCommunityWeb/PetCommunityBack, pull requests merged in 2023-08, with the labels that each got.

#6 fix: 로그인, 회원가입 관련 수정
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/common/security/JwtAuthenticationFilter.java
  src/main/java/com/example/petback/user/controller/UserController.java
  src/main/java/com/example/petback/user/dto/LoginRequestDto.java
  src/main/java/com/example/petback/user/dto/SignupRequestDto.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/service/UserService.java
Labels: enhancement

#7 [feat] 병원관련 CRUD 추가
  src/main/java/com/example/petback/common/domain/Address.java
  src/main/java/com/example/petback/hospital/controller/HospitalController.java
  src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java
  src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/hospital/repository/HospitalRepository.java
  src/main/java/com/example/petback/hospital/service/HospitalService.java
  src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java
  src/main/java/com/example/petback/user/entity/User.java
Labels: enhancement

#9 [feat] Feed CRUD 추가
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/dto/FeedRequestDto.java
  src/main/java/com/example/petback/feed/dto/FeedResponseDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/repository/FeedRepository.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
  src/main/java/com/example/petback/user/entity/User.java
Labels: enhancement

#12 feat: 실시간 채팅 기능 구현
  build.gradle
  src/main/java/com/example/petback/chat/config/WebSockConfig.java
  src/main/java/com/example/petback/chat/config/WebSocketHandler.java
  src/main/java/com/example/petback/chat/controller/ChatController.java
  src/main/java/com/example/petback/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/example/petback/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/example/petback/chat/dto/MessageDto.java
  src/main/java/com/example/petback/chat/dto/RoomDto.java
  src/main/java/com/example/petback/chat/dto/RoomRequestDto.java
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/main/java/com/example/petback/chat/entity/ChatRoom.java
  src/main/java/com/example/petback/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/petback/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/petback/chat/service/ChatService.java
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/common/jwt/JwtUtil.java
  src/main/java/com/example/petback/user/dto/SignupRequestDto.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/repository/UserRepository.java
  src/main/java/com/example/petback/user/service/UserService.java
Labels: enhancement

#15 [Refactor] ChatService 인터페이스와 구현체 적용
  src/main/java/com/example/petback/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/example/petback/chat/dto/MessageDto.java
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/main/java/com/example/petback/chat/entity/ChatRoom.java
  src/main/java/com/example/petback/chat/service/ChatService.java
  src/main/java/com/example/petback/chat/service/ChatServiceImpl.java
Labels: refactor

#16 [Fix] 병원 생성, 수정시에 진료동물 종류, 진료과목 추가
  src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java
  src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java
  src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java
  src/main/java/com/example/petback/hospitalspecies/repository/HospitalSpeciesRepository.java
  src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java
  src/main/java/com/example/petback/hospitalsubject/repository/HospitalSubjectRepository.java
  src/main/java/com/example/petback/species/SpeciesEnum.java
  src/main/java/com/example/petback/species/entity/Species.java
  src/main/java/com/example/petback/species/repository/SpeciesRepository.java
  src/main/java/com/example/petback/species/service/SpeciesService.java
  src/main/java/com/example/petback/subject/SubjectEnum.java
  src/main/java/com/example/petback/subject/entity/Subject.java
  src/main/java/com/example/petback/subject/repository/SubjectRepository.java
  src/main/java/com/example/petback/subject/service/SubjectService.java
  src/main/java/com/example/petback/user/entity/User.java
Labels: enhancement

#18 [feat] feed 에 댓글기능 추가 (댓글 작성, 수정, 삭제)
  src/main/java/com/example/petback/comment/controller/CommentController.java
  src/main/java/com/example/petback/comment/dto/CommentRequestDto.java
  src/main/java/com/example/petback/comment/dto/CommentResponseDto.java
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/comment/repository/CommentRepository.java
  src/main/java/com/example/petback/comment/service/CommentService.java
  src/main/java/com/example/petback/comment/service/CommentServiceImpl.java
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/feed/dto/FeedResponseDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
Labels: enhancement

#21 [Feat] 알람 기능 구현
  src/main/java/com/example/petback/PetBackApplication.java
  src/main/java/com/example/petback/notification/controller/NotificationController.java
  src/main/java/com/example/petback/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/petback/notification/entity/Notification.java
  src/main/java/com/example/petback/notification/repository/NotificationRepository.java
  src/main/java/com/example/petback/notification/service/NotificationService.java
  src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/petback/reservation/controller/ReservationController.java
  src/main/java/com/example/petback/reservation/entity/Reservation.java
  src/main/java/com/example/petback/reservation/event/EventPublisher.java
  src/main/java/com/example/petback/reservation/event/ReservationEvent.java
  src/main/java/com/example/petback/reservation/event/ReservationEventListener.java
  src/main/java/com/example/petback/reservation/repository/ReservationRepository.java
  src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
  src/main/java/com/example/petback/user/entity/User.java
Labels: enhancement

#25 [Refactor] JPA flush 제거
  src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
Labels: refactor

#26 [feat] 피드 좋아요 기능
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/dto/FeedResponseDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/entity/FeedLike.java
  src/main/java/com/example/petback/feed/repository/FeedLikeRepository.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
Labels: enhancement

#29 [Feat] notification Controller 테스트 코드 작성
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/notification/entity/Notification.java
  src/test/java/com/example/petback/notification/controller/NotificationControllerTest.java
Labels: enhancement

#31 [Feat] Cors관련 설정 추가
  src/main/java/com/example/petback/common/config/CorsConfig.java
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
Labels: enhancement

#33 [feat] Feed 관련 (CRUD, 좋아요, 댓글작성) 테스트 코드 완성
  src/main/java/com/example/petback/comment/controller/CommentController.java
  src/main/java/com/example/petback/comment/dto/CommentRequestDto.java
  src/main/java/com/example/petback/comment/dto/CommentResponseDto.java
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/comment/service/CommentService.java
  src/main/java/com/example/petback/comment/service/CommentServiceImpl.java
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/dto/FeedRequestDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/repository/FeedRepository.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
  src/test/java/com/example/petback/comment/controller/FeedCommentControllerTest.java
  src/test/java/com/example/petback/feed/controller/FeedControllerTest.java
Labels: enhancement

#34 [Feat] 회원가입 기능 관련, 팁 관련 완성
  src/main/java/com/example/petback/common/advice/AuthRequestDto.java
  src/main/java/com/example/petback/common/security/JwtAuthenticationFilter.java
  src/main/java/com/example/petback/tip/controller/TipContorller.java
  src/main/java/com/example/petback/tip/dto/TipListResponseDto.java
  src/main/java/com/example/petback/tip/dto/TipRequestDto.java
  src/main/java/com/example/petback/tip/dto/TipResponseDto.java
  src/main/java/com/example/petback/tip/entity/Tip.java
  src/main/java/com/example/petback/tip/entity/TipLike.java
  src/main/java/com/example/petback/tip/repository/TipLikeRepository.java
  src/main/java/com/example/petback/tip/repository/TipRepository.java
  src/main/java/com/example/petback/tip/service/TipService.java
  src/main/java/com/example/petback/tip/service/TipServiceImpl.java
  src/main/java/com/example/petback/user/controller/UserController.java
  src/main/java/com/example/petback/user/dto/LoginRequestDto.java
  src/main/java/com/example/petback/user/dto/ProfileRequestDto.java
  src/main/java/com/example/petback/user/dto/ProfileResponseDto.java
  src/main/java/com/example/petback/user/dto/SignupRequestDto.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/service/UserService.java
Labels: enhancement

#36 [Fix] 회원가입 시에 역할 추가
  src/main/java/com/example/petback/user/dto/SignupRequestDto.java
Labels: bug, enhancement

#49 [Feat] refreshToken 적용
  build.gradle
  src/main/java/com/example/petback/common/advice/ApiResponseDto.java
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/common/jwt/JwtUtil.java
  src/main/java/com/example/petback/common/jwt/RefreshToken.java
  src/main/java/com/example/petback/common/security/JwtAuthenticationFilter.java
  src/main/java/com/example/petback/common/security/JwtAuthorizationFilter.java
  src/main/java/com/example/petback/user/controller/UserController.java
  src/main/java/com/example/petback/user/dto/TokenRequestDto.java
  src/main/java/com/example/petback/user/repository/RefreshTokenRepository.java
  src/main/java/com/example/petback/user/service/RefreshTokenService.java
  src/main/java/com/example/petback/user/service/RefreshTokenServiceImpl.java
  src/main/java/com/example/petback/user/service/UserService.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
  src/test/java/com/example/petback/comment/controller/FeedCommentControllerTest.java
  src/test/java/com/example/petback/feed/controller/FeedControllerTest.java
  src/test/java/com/example/petback/hospital/controller/HospitalControllerTest.java
  src/test/java/com/example/petback/notification/controller/NotificationControllerTest.java
  src/test/java/com/example/petback/reservation/controller/ReservationControllerTest.java
  src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
  src/test/java/com/example/petback/user/controller/UserControllerTest.java
Labels: enhancement

#51 [Refactor] refreshToken 만료시 exception 처리 및 클라이언트에 응답
  src/main/java/com/example/petback/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/petback/user/repository/RefreshTokenRepository.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: refactor

#55 [Fix] CI 빌드 되도록 수정
  src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
  src/test/java/com/example/petback/user/controller/UserControllerTest.java
Labels: enhancement

#58 [Feat] CD 환경 구축
  .github/workflows/gradle.yml
  appspec.yml
  build.gradle
  build.gradle.kts
  scripts/start.sh
  scripts/stop.sh
Labels: enhancement
