Repository PetCommunityWeb/PetCommunityBack, pull requests merged in 2023-09, with the labels that each got.

#60 [Feat] access = AccessLevel.PROTECTED 옵션 추가
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/common/advice/ApiResponseDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/entity/FeedLike.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java
  src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java
  src/main/java/com/example/petback/reservation/entity/Reservation.java
  src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java
  src/main/java/com/example/petback/review/entity/Review.java
  src/main/java/com/example/petback/species/entity/Species.java
  src/main/java/com/example/petback/subject/entity/Subject.java
  src/main/java/com/example/petback/tip/entity/Tip.java
  src/main/java/com/example/petback/tip/entity/TipLike.java
  src/main/java/com/example/petback/user/dto/SignupRequestDto.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/service/UserService.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
  src/test/java/com/example/petback/feed/controller/FeedControllerTest.java
  src/test/java/com/example/petback/user/controller/UserControllerTest.java
Labels: refactor

#63 [Docs] readme 작성
  README.md
  image/ServiceArchitecture.png
Labels: enhancement

#64 [Refactor] UTC 기준 시간 변경
  src/main/java/com/example/petback/chat/config/WebSocketHandler.java
  src/main/java/com/example/petback/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/example/petback/chat/dto/MessageDto.java
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/test/java/com/example/petback/user/controller/UserControllerTest.java
Labels: enhancement, refactor

#65 [Refactor] 알림기능 리팩터링
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/petback/notification/controller/NotificationController.java
  src/main/java/com/example/petback/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/petback/notification/entity/Notification.java
  src/main/java/com/example/petback/notification/repository/NotificationRepository.java
  src/main/java/com/example/petback/notification/service/NotificationService.java
  src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/petback/reservation/repository/ReservationRepository.java
  src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
Labels: enhancement, refactor

#67 [Feature]예약가능 슬롯 자동 추가
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/main/java/com/example/petback/chat/entity/ChatRoom.java
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/feed/entity/FeedLike.java
  src/main/java/com/example/petback/hospital/OperatingDay.java
  src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java
  src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java
  src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java
  src/main/java/com/example/petback/reservationslot/service/ReservationSlotScheduler.java
  src/main/java/com/example/petback/tip/controller/TipContorller.java
  src/main/java/com/example/petback/tip/entity/Tip.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
  src/test/java/com/example/petback/hospital/controller/HospitalControllerTest.java
  src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
Labels: enhancement

#70 [Refactor] refreshToken 만료시 exception handling
  src/main/java/com/example/petback/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/petback/common/jwt/JwtUtil.java
  src/main/java/com/example/petback/common/security/JwtAuthorizationFilter.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: enhancement, refactor

#75 [Feature] 병원, 알림, 피드, 예약, 리뷰 캐싱 적용
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/example/petback/common/config/CacheConfig.java
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/dto/FeedListResponseDto.java
  src/main/java/com/example/petback/feed/dto/FeedResponseDto.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
  src/main/java/com/example/petback/hospital/controller/HospitalController.java
  src/main/java/com/example/petback/hospital/dto/HospitalListResponseDto.java
  src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java
  src/main/java/com/example/petback/hospital/service/HospitalService.java
  src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java
  src/main/java/com/example/petback/notification/controller/NotificationController.java
  src/main/java/com/example/petback/notification/dto/NotificationListResponseDto.java
  src/main/java/com/example/petback/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/petback/notification/service/NotificationService.java
  src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/petback/reservation/controller/ReservationController.java
  src/main/java/com/example/petback/reservation/dto/ReservationListResponseDto.java
  src/main/java/com/example/petback/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/petback/reservation/service/ReservationService.java
  src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
  src/main/java/com/example/petback/review/controller/ReviewController.java
  src/main/java/com/example/petback/review/dto/ReviewListResponseDto.java
  src/main/java/com/example/petback/review/service/ReviewService.java
  src/main/java/com/example/petback/review/service/ReviewServiceImpl.java
  src/main/java/com/example/petback/tip/controller/TipContorller.java
Labels: enhancement

#77 refactor: 채팅방 삭제
  src/main/java/com/example/petback/chat/controller/ChatController.java
  src/main/java/com/example/petback/chat/dto/RoomDto.java
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/main/java/com/example/petback/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/petback/chat/service/ChatService.java
  src/main/java/com/example/petback/chat/service/ChatServiceImpl.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: enhancement

#79 [Feature] Hard Delete로 변경
  src/main/java/com/example/petback/comment/dto/CommentResponseDto.java
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/comment/service/CommentServiceImpl.java
  src/main/java/com/example/petback/feed/dto/FeedResponseDto.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/entity/FeedLike.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/notification/entity/Notification.java
  src/main/java/com/example/petback/reservation/entity/Reservation.java
  src/main/java/com/example/petback/review/entity/Review.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
  src/test/java/com/example/petback/comment/controller/FeedCommentControllerTest.java
Labels: enhancement, refactor

#85 [Refactor] tip 일부 수정
  src/main/java/com/example/petback/hospital/controller/HospitalController.java
  src/main/java/com/example/petback/reservationslot/service/ReservationSlotScheduler.java
  src/main/java/com/example/petback/tip/controller/TipContorller.java
  src/main/java/com/example/petback/tip/entity/Tip.java
  src/main/java/com/example/petback/tip/entity/TipLike.java
  src/main/java/com/example/petback/tip/repository/TipLikeRepository.java
  src/main/java/com/example/petback/tip/service/TipService.java
  src/main/java/com/example/petback/tip/service/TipServiceImpl.java
  src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
Labels: refactor

#86 [Refactor] 탈퇴 회원 복구로직 수정
  src/main/java/com/example/petback/user/dto/UserDto.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/repository/UserRepository.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: refactor

#89 [Feature] 피드 좋아요 순 조회 추가 및 캐싱처리
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/repository/FeedRepository.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
Labels: enhancement

#92 [Refactor] 채팅방 1대1로 변경
  src/main/java/com/example/petback/chat/config/WebSocketHandler.java
  src/main/java/com/example/petback/chat/controller/ChatController.java
  src/main/java/com/example/petback/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/example/petback/chat/dto/RoomDto.java
  src/main/java/com/example/petback/chat/dto/RoomRequestDto.java
  src/main/java/com/example/petback/chat/entity/ChatMessage.java
  src/main/java/com/example/petback/chat/entity/ChatRoom.java
  src/main/java/com/example/petback/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/petback/chat/service/ChatService.java
  src/main/java/com/example/petback/chat/service/ChatServiceImpl.java
  src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java
  src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java
  src/main/java/com/example/petback/user/controller/UserController.java
  src/main/java/com/example/petback/user/repository/UserRepository.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: enhancement, refactor

#93 [Refactor] 회원 복구시 데이터 복구
  src/main/java/com/example/petback/comment/entity/Comment.java
  src/main/java/com/example/petback/comment/repository/CommentRepository.java
  src/main/java/com/example/petback/feed/entity/Feed.java
  src/main/java/com/example/petback/feed/entity/FeedLike.java
  src/main/java/com/example/petback/feed/repository/FeedLikeRepository.java
  src/main/java/com/example/petback/feed/repository/FeedRepository.java
  src/main/java/com/example/petback/hospital/entity/Hospital.java
  src/main/java/com/example/petback/hospital/repository/HospitalRepository.java
  src/main/java/com/example/petback/reservation/entity/Reservation.java
  src/main/java/com/example/petback/reservation/repository/ReservationRepository.java
  src/main/java/com/example/petback/review/entity/Review.java
  src/main/java/com/example/petback/review/repository/ReviewRepository.java
  src/main/java/com/example/petback/tip/entity/Tip.java
  src/main/java/com/example/petback/tip/entity/TipLike.java
  src/main/java/com/example/petback/tip/repository/TipLikeRepository.java
  src/main/java/com/example/petback/tip/repository/TipRepository.java
  src/main/java/com/example/petback/user/controller/UserController.java
  src/main/java/com/example/petback/user/entity/User.java
  src/main/java/com/example/petback/user/service/UserServiceImpl.java
Labels: refactor

#96 feat: target group health check 추가
  build.gradle
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
Labels: enhancement

#97 [Feature] cors config 수정
  src/main/java/com/example/petback/common/config/CorsConfig.java
Labels: bug

#98 [Feature] allowedOrigin 수정
  src/main/java/com/example/petback/common/config/CorsConfig.java
Labels: bug

#99 feat: allowedOrigin ALB DNS로 수정 및 health check controller 직접생성
  src/main/java/com/example/petback/common/config/CorsConfig.java
  src/main/java/com/example/petback/common/controller/HealthCheckController.java
Labels: bug

#100 [Feature] allowedOrigin front로 다시 수정
  src/main/java/com/example/petback/common/config/CorsConfig.java
Labels: bug

#102 [Feature] 피드 댓글 순 조회 추가
  src/main/java/com/example/petback/feed/controller/FeedController.java
  src/main/java/com/example/petback/feed/repository/FeedRepository.java
  src/main/java/com/example/petback/feed/service/FeedService.java
  src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
Labels: enhancement

#95 [Feature] oauth2 추가
  .gitignore
  build.gradle
  src/main/java/com/example/petback/chat/dto/RoomDto.java
  src/main/java/com/example/petback/chat/entity/ChatRoom.java
  src/main/java/com/example/petback/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/petback/chat/service/ChatServiceImpl.java
  src/main/java/com/example/petback/common/config/WebSecurityConfig.java
  src/main/java/com/example/petback/oauth2/CustomOAuth2UserService.java
  src/main/java/com/example/petback/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/example/petback/oauth2/dto/OAuthAttributes.java
  src/main/java/com/example/petback/oauth2/dto/SessionUser.java
  src/main/java/com/example/petback/user/entity/User.java
Labels: enhancement

#106 [Fix] 알림기능 스케쥴러관련 로드밸런서 적용시 문제 해결
  build.gradle
  src/main/java/com/example/petback/common/config/SchedulerConfig.java
  src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/petback/reservationslot/service/ReservationSlotScheduler.java
Labels: bug, enhancement, refactor

#110 [Feature] 팁 제목/내용 별 검색 기능 추가
  build.gradle
  src/main/java/com/example/petback/common/controller/HealthCheckController.java
  src/main/java/com/example/petback/tip/controller/TipContorller.java
  src/main/java/com/example/petback/tip/repository/TipRepository.java
  src/main/java/com/example/petback/tip/service/TipService.java
  src/main/java/com/example/petback/tip/service/TipServiceImpl.java
  src/main/java/com/example/petback/user/controller/UserController.java
Labels: enhancement

#113 [Feature] 팁 작성시 파일 다중 첨부
  src/main/java/com/example/petback/tip/dto/TipRequestDto.java
  src/main/java/com/example/petback/tip/entity/Tip.java
Labels: enhancement
